name: Generar documentació Pydoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instal·lar dependències
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Generar documentació amb Pydoc
        run: |
          source venv/bin/activate
          mkdir -p docs
          pydoc --html blog -o docs/blog.html

      - name: Forçar commit i push de la documentació
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/blog.html || true
          git commit -m "Actualitza documentació Pydoc (forçat)" || echo "Sense canvis"
          git push origin main